# -*- coding: utf-8 -*-
"""local_llm_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYDNLgYjJsYTXNI6snv8A3yV6PfxNPgZ
"""

!nvidia-smi

!pip install accelerate flask flask-ngrok pyngrok
!pip install "transformers==4.43.0" "huggingface_hub==0.34.1" bitsandbytes

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# --- Hard-coded configuration ---
MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"
MAX_NEW_TOKENS = 512
TEMPERATURE = 0.7
TOP_P = 0.9

# 8-bit quantization config for T4 GPU
bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_threshold=6.0,
    llm_int8_enable_fp32_cpu_offload=True
)

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("Loading model (this may take a few minutes)...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="cpu", #change to auto for gpu use
    torch_dtype=torch.bfloat16  # T4 needs float16, not bfloat16
)

print("Model loaded successfully!")

def generate_response(prompt: str) -> str:
    """Run the prompt through the LLM and return the generated text."""
    inputs = tokenizer(prompt, return_tensors="pt")
    device = next(model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            temperature=TEMPERATURE,
            top_p=TOP_P,
            do_sample=True,
        )

    # Decode only the newly generated tokens (skip the prompt)
    input_length = inputs["input_ids"].shape[1]
    new_tokens = outputs[0][input_length:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True)


# Quick sanity check
print(generate_response("Say hello in one sentence."))

from flask import Flask, request, jsonify
from pyngrok import ngrok
import threading

app = Flask(__name__)

@app.route("/generate", methods=["POST"])
def generate():
    """
    POST /generate
    Body (JSON): { "prompt": "Your prompt here" }
    Response (JSON): { "response": "LLM output" }
    """
    data = request.get_json(force=True, silent=True)
    if not data or "prompt" not in data:
        return jsonify({"error": "Request body must be JSON with a 'prompt' field."}), 400

    prompt = data["prompt"]
    try:
        result = generate_response(prompt)
        return jsonify({"response": result})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# Expose the local Flask server via ngrok so it's reachable from outside Colab
public_url = ngrok.connect(5000)
print(f"Public API URL: {public_url}/generate")
print("Send a POST request with JSON body: { \"prompt\": \"your text\" }")

# Run Flask in a background thread so the notebook cell doesn't block
threading.Thread(target=lambda: app.run(port=5000, use_reloader=False)).start()

# --- Example: test the API from inside the notebook ---
import requests

response = requests.post(
    "http://localhost:5000/generate",
    json={"prompt": "Explain gravity in one paragraph."}
)
print(response.json())